```{r}
library(tidyverse)
library(dplyr)

sets <- read_csv('sets.csv')
themes <- read_csv('themes.csv')
parts <- read_csv('parts.csv')
part_categories <- read_csv('part_categories.csv')
inventory_parts <- read_csv('inventory_parts.csv')
inventories <- read_csv('inventories.csv')
colors <- read_csv('colors.csv')
```

Joining parts and part_categories

```{r}
parts %>%
  inner_join(part_categories, by = c("part_cat_id" = "id"))

part_categories %>%
  inner_join(parts, by = c("id" = "part_cat_id"))

parts %>%
  inner_join(part_categories, by = c("part_cat_id" = "id"), suffix = c("_part", "_category"))
```

```{r}
inventory_parts
parts

parts %>%
  inner_join(inventory_parts, by = "part_num")
```
```{r}
sets
inventories
inventory_parts

sets %>%
  inner_join(inventories, by="set_num") %>%
  inner_join(inventory_parts, by=c("id" = "inventory_id")) %>%
  inner_join(colors, by = c("color_id" = "id"), suffix = c("_set", "_color")) 
```
Left and Right Joins

```{r}

inventory_parts_joined <- sets %>%
  inner_join(inventories, by="set_num") %>%
  inner_join(inventory_parts, by=c("id" = "inventory_id")) %>%
  inner_join(colors, by = c("color_id" = "id"), suffix = c("_set", "_color")) 

# left table
millennium_falcon <- inventory_parts_joined %>%
  filter(set_num == "7965-1")

# right table
star_destroyer <- inventory_parts_joined %>%
  filter(set_num == "75190-1")

millennium_falcon
star_destroyer

# IDs = part_num, color_id

millennium_falcon %>%
  left_join(star_destroyer, by=c("part_num", "color_id"), suffix = c("_falcon","_star_destroyer"))

```
```{r}
# left table
parts %>%
  count(part_cat_id) %>%
  # right table
  right_join(part_categories, by=c("part_cat_id" = "id")) %>%
  filter(is.na(n))
```

